apiVersion: v1
kind: Service
metadata:
  name: {{ include "aeos.fullname" . }}
  labels: {{- include "aeos.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "aeos.selector" . | nindent 4 }}
  ports:
    - { name: http, port: {{ .Values.service.port }}, targetPort: http, protocol: TCP }
