import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { z } from 'zod';
import type { AgentConfig, CredentialProfile } from '@aeos/contracts';
import type { HarnessProfile } from '@aeos/provider-core';

/** Same contract as provider-claude's resolver — the store itself is P2.M3. */
export interface SecretResolver {
  resolve(secretRef: string): Promise<string>;
}

export interface BuildCodexProfileOptions {
  agent: AgentConfig;
  /** Absolute path of the agent's directory; harness state goes under `harness/codex`. */
  agentDir: string;
  credential: CredentialProfile;
  secrets: SecretResolver;
  /**
   * Subscription slot → persistent login home. Codex keeps ChatGPT-login
   * state under `CODEX_HOME/auth.json`, so a slot maps to its own home dir
   * (one `codex login` inside binds one account). Required for
   * `subscription` profiles; api-key/gateway kinds are per-agent hermetic.
   */
  subscriptionHomeFor?: (slot: string) => string;
}

export class MissingSubscriptionHomeError extends Error {
  constructor(slot: string) {
    super(
      `credential kind "subscription" (slot "${slot}") requires subscriptionHomeFor to map the slot to its persistent login home`,
    );
    this.name = 'MissingSubscriptionHomeError';
  }
}

const GeneratedConfigSchema = z.object({
  generatedBy: z.literal('@aeos/provider-codex'),
  agentId: z.string(),
});
export type GeneratedConfig = z.infer<typeof GeneratedConfigSchema>;

/** Sidecar proving the config.toml is ours (parse-then-preserve on regen). */
export function parseGeneratedSidecar(raw: string): GeneratedConfig {
  return GeneratedConfigSchema.parse(JSON.parse(raw));
}

async function credentialEnv(
  credential: CredentialProfile,
  secrets: SecretResolver,
): Promise<Record<string, string>> {
  switch (credential.kind) {
    case 'api-key':
      return { OPENAI_API_KEY: await secrets.resolve(credential.secretRef) };
    case 'gateway':
      // codex speaks OpenAI wire protocol — gateway support rides OPENAI_BASE_URL
      return {
        OPENAI_BASE_URL: credential.baseUrl,
        OPENAI_API_KEY: await secrets.resolve(credential.secretRef),
      };
    case 'subscription':
      // login state lives in the slot's own persistent home (see below)
      return {
        AEOS_CREDENTIAL_PASSTHROUGH: 'subscription',
        AEOS_SUBSCRIPTION_SLOT: credential.slot,
      };
  }
}

/**
 * Hermetic Codex profile (spec §9): per-agent `CODEX_HOME` with a generated
 * minimal `config.toml`. Zero references to `$HOME` defaults — all state
 * lives inside the profile dir; `subscription` profiles point CODEX_HOME at
 * the slot's persistent login home so N agents share one bound account
 * per slot while config stays per-agent.
 */
export async function buildCodexProfile(opts: BuildCodexProfileOptions): Promise<HarnessProfile> {
  const rootDir = path.join(opts.agentDir, 'harness', 'codex');
  await mkdir(rootDir, { recursive: true });

  await writeFile(
    path.join(rootDir, 'config.toml'),
    [
      '# generated by @aeos/provider-codex — do not hand-edit',
      'check_updates = false',
      '',
    ].join('\n'),
  );
  await writeFile(
    path.join(rootDir, '.aeos-generated.json'),
    JSON.stringify({
      generatedBy: '@aeos/provider-codex',
      agentId: opts.agent.id,
    } satisfies GeneratedConfig),
  );

  let codeHome = rootDir;
  if (opts.credential.kind === 'subscription') {
    if (opts.subscriptionHomeFor === undefined) {
      throw new MissingSubscriptionHomeError(opts.credential.slot);
    }
    codeHome = opts.subscriptionHomeFor(opts.credential.slot);
  }

  const env = {
    AEOS_CREDENTIAL_PROFILE_ID: opts.credential.id,
    ...(await credentialEnv(opts.credential, opts.secrets)),
    CODEX_HOME: codeHome,
  };

  return { rootDir, env, argv: [] };
}
