import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

/**
 * `aeos service install|uninstall|status` (P4.M3.T1, spec §16): run aeosd
 * as a per-user service — a systemd user unit on Linux, a LaunchAgent on
 * macOS — so it starts at login/boot and restarts on failure.
 *
 * Detached runners outlive the daemon by design (spec §10 crash matrix:
 * "daemon restart → re-adopt runners"). The service manager must therefore
 * stop ONLY the daemon process: `KillMode=process` (systemd) and
 * `AbandonProcessGroup` (launchd). The default of killing the whole group
 * would silently turn every daemon restart into a runner crash.
 */

export interface ServiceSpec {
  /** Absolute node executable. */
  node: string;
  /** Absolute path of aeosd's main.js. */
  aeosd: string;
  home: string;
  port: number;
  host?: string;
  /** File holding the API token (required by aeosd for non-loopback hosts). */
  tokenFile?: string;
}

export const SYSTEMD_UNIT = 'aeosd.service';
export const LAUNCHD_LABEL = 'dev.aeos.aeosd';

function environment(spec: ServiceSpec): Array<[string, string]> {
  return [
    ['AEOS_HOME', spec.home],
    ['AEOS_PORT', String(spec.port)],
    ...(spec.host === undefined ? [] : ([['AEOS_HOST', spec.host]] as Array<[string, string]>)),
    ...(spec.tokenFile === undefined ? [] : ([['AEOS_API_TOKEN_FILE', spec.tokenFile]] as Array<[string, string]>)),
  ];
}

/** systemd quoting: a word with spaces, quotes or backslashes goes in "…" with escapes. */
const systemdQuote = (value: string): string => (/^[A-Za-z0-9_@%+=:,./-]+$/.test(value) ? value : `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`);

export function renderSystemdUnit(spec: ServiceSpec): string {
  return [
    '# Generated by `aeos service install` — re-run it to regenerate.',
    '[Unit]',
    'Description=AEOS daemon (aeosd)',
    'Documentation=https://github.com/mirrorfolio-idea-labs/AEOS',
    'After=network-online.target',
    'Wants=network-online.target',
    '',
    '[Service]',
    'Type=simple',
    `ExecStart=${systemdQuote(spec.node)} ${systemdQuote(spec.aeosd)} run`,
    ...environment(spec).map(([k, v]) => `Environment=${systemdQuote(`${k}=${v}`)}`),
    'Restart=on-failure',
    'RestartSec=5',
    '# runners are detached and re-adopted after a daemon restart (spec §10):',
    '# stop only the daemon process, never its runners',
    'KillMode=process',
    'NoNewPrivileges=true',
    '',
    '[Install]',
    'WantedBy=default.target',
    '',
  ].join('\n');
}

const xml = (value: string): string => value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

export function renderLaunchdPlist(spec: ServiceSpec): string {
  const logs = path.join(spec.home, 'logs');
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
    '<!-- Generated by `aeos service install` — re-run it to regenerate. -->',
    '<plist version="1.0">',
    '<dict>',
    `  <key>Label</key><string>${LAUNCHD_LABEL}</string>`,
    '  <key>ProgramArguments</key>',
    '  <array>',
    `    <string>${xml(spec.node)}</string>`,
    `    <string>${xml(spec.aeosd)}</string>`,
    '    <string>run</string>',
    '  </array>',
    '  <key>EnvironmentVariables</key>',
    '  <dict>',
    ...environment(spec).map(([k, v]) => `    <key>${k}</key><string>${xml(v)}</string>`),
    '  </dict>',
    '  <key>RunAtLoad</key><true/>',
    '  <key>KeepAlive</key>',
    '  <dict><key>SuccessfulExit</key><false/></dict>',
    '  <key>ThrottleInterval</key><integer>5</integer>',
    '  <!-- runners are detached and re-adopted after a daemon restart (spec §10) -->',
    '  <key>AbandonProcessGroup</key><true/>',
    `  <key>StandardOutPath</key><string>${xml(path.join(logs, 'aeosd.out.log'))}</string>`,
    `  <key>StandardErrorPath</key><string>${xml(path.join(logs, 'aeosd.err.log'))}</string>`,
    '</dict>',
    '</plist>',
    '',
  ].join('\n');
}

export type ServicePlatform = 'linux' | 'darwin';

export interface ServicePlan {
  file: string;
  content: string;
  /** Commands to activate it, in order; `optional` ones may fail with a warning. */
  commands: Array<{ argv: string[]; optional?: boolean; why: string }>;
}

export function planInstall(spec: ServiceSpec, platform: ServicePlatform, homedir: string, user: { name: string; uid: number }): ServicePlan {
  if (platform === 'linux') {
    return {
      file: path.join(homedir, '.config', 'systemd', 'user', SYSTEMD_UNIT),
      content: renderSystemdUnit(spec),
      commands: [
        { argv: ['systemctl', '--user', 'daemon-reload'], why: 'load the unit' },
        { argv: ['systemctl', '--user', 'enable', '--now', SYSTEMD_UNIT], why: 'start now and at every login' },
        {
          argv: ['loginctl', 'enable-linger', user.name],
          optional: true,
          why: 'keep it running after logout and start it at boot (may need admin rights)',
        },
      ],
    };
  }
  const file = path.join(homedir, 'Library', 'LaunchAgents', `${LAUNCHD_LABEL}.plist`);
  return {
    file,
    content: renderLaunchdPlist(spec),
    commands: [
      { argv: ['launchctl', 'bootout', `gui/${String(user.uid)}/${LAUNCHD_LABEL}`], optional: true, why: 'unload a previous version' },
      { argv: ['launchctl', 'bootstrap', `gui/${String(user.uid)}`, file], why: 'load now and at every login' },
    ],
  };
}

export function planUninstall(platform: ServicePlatform, homedir: string, user: { uid: number }): ServicePlan {
  if (platform === 'linux') {
    return {
      file: path.join(homedir, '.config', 'systemd', 'user', SYSTEMD_UNIT),
      content: '',
      commands: [
        { argv: ['systemctl', '--user', 'disable', '--now', SYSTEMD_UNIT], optional: true, why: 'stop and disable' },
        { argv: ['systemctl', '--user', 'daemon-reload'], optional: true, why: 'forget the unit' },
      ],
    };
  }
  return {
    file: path.join(homedir, 'Library', 'LaunchAgents', `${LAUNCHD_LABEL}.plist`),
    content: '',
    commands: [{ argv: ['launchctl', 'bootout', `gui/${String(user.uid)}/${LAUNCHD_LABEL}`], optional: true, why: 'unload' }],
  };
}

/** Resolve aeosd's entry: an explicit path, else `aeosd` on PATH (resolved through its symlink). */
export function resolveAeosd(explicit: string | undefined): string {
  if (explicit !== undefined) return path.resolve(explicit);
  for (const dir of (process.env['PATH'] ?? '').split(path.delimiter)) {
    const candidate = path.join(dir, 'aeosd');
    if (fs.existsSync(candidate)) return fs.realpathSync(candidate);
  }
  throw new Error('cannot find aeosd on PATH — pass --aeosd /path/to/aeosd/dist/main.js');
}

export interface ServiceIo {
  out: (line: string) => void;
  err: (line: string) => void;
}

export function applyPlan(plan: ServicePlan, io: ServiceIo, remove: boolean): number {
  if (remove) {
    for (const cmd of plan.commands) run(cmd, io);
    fs.rmSync(plan.file, { force: true });
    io.out(`removed ${plan.file}`);
    return 0;
  }
  fs.mkdirSync(path.dirname(plan.file), { recursive: true });
  fs.writeFileSync(plan.file, plan.content);
  io.out(`wrote ${plan.file}`);
  for (const cmd of plan.commands) {
    if (!run(cmd, io)) return 1;
  }
  return 0;
}

function run(cmd: ServicePlan['commands'][number], io: ServiceIo): boolean {
  const result = spawnSync(cmd.argv[0] as string, cmd.argv.slice(1), { encoding: 'utf8' });
  if (result.status === 0) {
    io.out(`ok: ${cmd.argv.join(' ')}  (${cmd.why})`);
    return true;
  }
  const detail = (result.stderr || result.stdout || String(result.error ?? '')).trim().split('\n')[0] ?? '';
  if (cmd.optional === true) {
    io.err(`warning: ${cmd.argv.join(' ')} failed — ${detail}. Without it: ${cmd.why}.`);
    return true;
  }
  io.err(`failed: ${cmd.argv.join(' ')} — ${detail}`);
  return false;
}

export const currentPlatform = (): ServicePlatform | undefined =>
  process.platform === 'linux' || process.platform === 'darwin' ? process.platform : undefined;

export const currentUser = (): { name: string; uid: number } => ({ name: os.userInfo().username, uid: os.userInfo().uid });
